remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jemoji
title: "Interpretable Control Competition"
description: "TL;DR submit an interpretable policy to address a control problem and win"

url: 'https://giorgia-nadizar.github.io/' # your main domain
baseurl: 'interpretable-control-competition/'
